

GET https://localhost:7271/donors/get/users/e7423bd8-8f9b-4060-b055-98a6298e0d5b
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlNzQyM2JkOC04ZjliLTQwNjAtYjA1NS05OGE2Mjk4ZTBkNWIiLCJ1bmlxdWVfbmFtZSI6IkpvaG5Eb2UiLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwianRpIjoiNjhhNTBjOWItZDc0ZS00YTcxLWI4NTgtMWNjYTg0MzAzYjc3IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiZG9ub3IiLCJleHAiOjE2OTA4MjI3MzMsImlzcyI6IlN1cnZleU1hbmFnZXJBcHBJc3N1ZXIiLCJhdWQiOiJTdXJ2ZXlNYW5hZ2VyQXBwQXVkaWVuY2UifQ.Mk5BAfzSEKcMrcjaVM5V3LFa15S-SWdUB32EELy62CI